image:
  repository: flybywiresim/api
  tag: latest
  pullPolicy: Always

replicas: 1

service:
  port: 3000

ingress:
  fqdn: ~
  tls:
    enabled: false
    issuer: ~

apm:
  active: false
  serverUrl: ~

api:
  logger:
    level: info
    format: json
  database:
    host: ~
    port: 3306
    database: fbw
    user: fbw
    password: somePassword
    logging: error
    connectionLimit: 5
    replicas: []
  redis:
    host: ~
    port: 6379
  telex:
    disableCleanup: false
    timeoutMin: 6
    discordWebhook: ~
  auth:
    secret: someSecret
    expires: 12h
  github:
    token: someToken
